
services:
  # Servicio Frontend
  frontend:
    build:
      context: ./frontend
      # No necesitas especificar dockerfile si est치 en la ubicaci칩n por defecto (./Dockerfile)
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # Servicio Backend
  backend:
    build:
      context: ./backend
      # No necesitas especificar dockerfile si est치 en la ubicaci칩n por defecto (./Dockerfile)
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: videogames_store
      DB_USERNAME: laravel
      DB_PASSWORD: laravel

  # Servicio de Base de Datos    
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: videogames_store
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  # Servicio phpMyAdmin    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  mysql_data: